### ISSUE TITLE
Client side tests action

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4104]
## Is your feature request related to a problem? Please describe 👀
Coming from the full team retro - the request was made for the client tests to run when a front-end PR is made.

## Describe the solution you'd like 🎁
Create a file in `.github/workflows` such as `client-tests.yaml` with the following:

```
name: Client tests

on:
  pull_request:
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Install dependencies
        run: cd ./client && rm -rf node_modules && yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

      - name: Run tests
        run: cd ./client && yarn test
```
