### ISSUE TITLE
Unable to configure mail with TLS on windows

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#6911]
## What went wrong? 😲

Configuring mail to use an external mail relay 

```
 mail:
   host: "smtp.gmail.com"
   port: "465"
   starttls: true
   username: "abcdev@gmail.com"
   password: "xxx-xxx-xxx"
   from: "abcdef@gmail.com"
   interval: 60 # in seconds
```

```
2025-03-12 16:57:29.570830200 [ERROR] <log_panics:130>:thread '<unnamed>' panicked at 'Unable to install rustls::crypto::ring default provider: CryptoProvider {
    cipher_suites: [
        TLS13_AES_256_GCM_SHA384,
        TLS13_AES_128_GCM_SHA256,
        TLS13_CHACHA20_POLY1305_SHA256,
        TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
        TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
        TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
        TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    ],
    kx_groups: [
        X25519,
        secp256r1,
        secp384r1,
    ],
    signature_verification_algorithms: WebPkiSupportedAlgorithms { all: [ .. ], mapping: [
        ECDSA_NISTP384_SHA384,
        ECDSA_NISTP256_SHA256,
        ED25519,
        RSA_PSS_SHA512,
        RSA_PSS_SHA384,
        RSA_PSS_SHA256,
        RSA_PKCS1_SHA512,
        RSA_PKCS1_SHA384,
        RSA_PKCS1_SHA256,
    ] },
    secure_random: Ring,
    key_provider: Ring,
}': server\src\certs.rs:56
2025-03-12 16:57:29.576578100 [ERROR] <log_panics:130>:thread '<unnamed>' panicked at 'panic in a function that cannot unwind': library\core\src\panicking.rs:221
```

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:
